export const productConstants = {
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
  GET_PRODUCT_BY_CATEGORY_SUCCESS: "GET_PRODUCT_BY_CATEGORY_SUCCESS",
  GET_PRODUCT_BY_CATEGORY_FAILURE: "GET_PRODUCT_BY_CATEGORY_FAILURE"
};