export const productConstants = {
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
  GET_PRODUCTS_BY_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_CATEGORY_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_FAILURE: "GET_PRODUCTS_BY_CATEGORY_FAILURE",
};

export const cartConstants = {
  GET_USER_CART_ITEMS_SUCCESS: "GET_USER_CART_ITEMS_SUCCESS",
  GET_USER_CART_ITEMS_FAILURE: "GET_USER_CART_ITEMS_FAILURE",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
};

export const userConstants = {
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FAILURE: "GET_USER_BY_ID_FAILURE",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_IN_SUCCESSE: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
};

export const orderConstants = {
  GET_All_ORDERS_SUCCESS: "GET_All_ORDERS_SUCCESS",
  GET_All_ORDERS_FAILURE: "GET_All_ORDERS_FAILURE",
  GET_USER_ORDERS_BY_USER_ID_SUCCESS: "GET_USER_ORDERS_BY_USER_ID_SUCCESS",
  GET_USER_ORDERS_BY_USER_ID_FAILURE: "GET_USER_ORDERS_BY_USER_ID_FAILURE",
  GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
  GET_ORDER_BY_ID_FAILURE: "GET_ORDER_BY_ID_FAILURE",
  SET_ORDER_SUCCESS: "SET_ORDER_SUCCESSS",
  SET_ORDER_FAILURE: "SET_ORDER_FAILURE",
  GET_ORDER_STATUS_SUCCESS: "GET_ORDER_STATUS_SUCCESS",
  GET_ORDER_STATUS_FAILURE: "GET_ORDER_STATUS_FAILURE",
  UPDATE_ORDER_PAY_STATUS_SUCCESS: "UPDATE_ORDER_PAY_STATUS_SUCCESS",
  UPDATE_ORDER_PAY_STATUS_FAILURE: "UPDATE_ORDER_PAY_STATUS_FAILURE",
  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAILURE: "UPDATE_ORDER_STATUS_FAILURE",
};

export const paymentConstants = {
  SET_PAYMENT_SUCCESS: "SET_PAYMENT_SUCCESS",
  SET_PAYMENT_FAILURE: "SET_PAYMENT_FAILURE",
};
