export const productConstants = {
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
  GET_PRODUCTS_BY_CATEGORY_SUCCESS: "GET_PRODUCTS_BY_CATEGORY_SUCCESS",
  GET_PRODUCTS_BY_CATEGORY_FAILURE: "GET_PRODUCTS_BY_CATEGORY_FAILURE"
};

export const cartConstants = {
  GET_USER_CART_ITEMS_SUCCESS : "GET_USER_CART_ITEMS_SUCCESS",
  GET_USER_CART_ITEMS_FAILURE : "GET_USER_CART_ITEMS_FAILURE",
  ADD_TO_CART_SUCCESS : "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE : "ADD_TO_CART_FAILURE",
};

export const userConstants = {
  GET_USER_BY_ID_SUCCESS : "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FAILURE : "GET_USER_BY_ID_FAILURE",

}

export const orderConstants = {
  GET_All_ORDERS_SUCCESS : "GET_All_ORDERS_SUCCESS",
  GET_All_ORDERS_FAILURE : "GET_All_ORDERS_FAILURE",

}